command /admin:
  permission: admin
  trigger:
    loop all entities in radius 5 of player:
      if name of loop-entity contains "&eDodge" or "&e0" or "&eMiss" or "&eEvade":
        kill loop-entity
      if name of loop-entity contains "&c0" or "&c1" or "&c2" or "&c3" or "&c4" or "&c5" or "&c6" or "&c7" or "&c8" or "&c9":
        kill loop-entity

every 1 hour:
  loop all entities in radius 5 of location at 1, 1, 1 in world "void":
    kill loop-entity   